### ISSUE TITLE
FetchAccountInfoAsync fails in Same-Day Microdeposits auth flow

### ISSUE THREAD

**Issue by aorlenko83** [viceroypenguin/Going.Plaid.NET#21]
In the Same-day microdeposits auth flow, after the successful account linking, the attemt to call FetchAccountInfoAsync ends with InvalidOperationException.
InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
Stack trace:
```System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[Going.Plaid.Entity.Balance]. Path: $.accounts[0].balances | LineNumber: 6 | BytePositionInLine: 23.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetDecimal(Decimal& value)
   at System.Text.Json.Utf8JsonReader.GetDecimal()
   at System.Text.Json.Serialization.Converters.DecimalConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonResumableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.NullableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Going.Plaid.PlaidClient.ResponseParser.BuildResponse[TResponse](HttpResponseMessage response)
   at Going.Plaid.PlaidClient.ResponseParser.ParseResponseAsync[TResponse]()```

In general the issue is that in other auth flows, after an account is linked successfully, the FetchAccountInfoAsync method (which is /auth/get Plaid call), returns the account with available "balance" information. So the account.balances object has non-null values. But in Same-day microdeposits flow, the "balances" property has all empty values. It causes exception thrown.

**Comment by viceroypenguin** [comment]
I've created PR #22. Do you have any way to test this from your code? If not, I'll do another point release and 🤞

**Comment by aorlenko83** [comment]
Maybe this would be helpful. This is what I'm receiving if doing direct Plaid call to /auth/get
![image](https://user-images.githubusercontent.com/49045994/105982061-7b527480-609f-11eb-8286-14b6aa61f018.png)

If 'Current' is the only field that needed to be fixed, then PR should do the job, thanks.

**Comment by viceroypenguin** [comment]
Awesome, thanks! New release v2.2.1 should give you what you need!
